# Generated by Django 2.2.3 on 2019-07-04 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='curriculum_grade',
            field=models.IntegerField(default=0, verbose_name='课程设计成绩'),
        ),
        migrations.CreateModel(
            name='CurriculumInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_id', models.CharField(max_length=16, unique=True, verbose_name='课程设计号')),
                ('curriculum_name', models.CharField(max_length=32, verbose_name='课程设计名称')),
                ('curriculum_content', models.CharField(max_length=1024, verbose_name='课程设计题目')),
                ('last_number', models.IntegerField(default=4, verbose_name='剩余人数')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.EmployeeInformation', verbose_name='员工号')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.MajorInformation', verbose_name='专业号')),
            ],
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='curriculum_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='APP01.CurriculumInformation', to_field='curriculum_id', verbose_name='课程设计编号'),
        ),
    ]
